## Remove URL for Github Pages
url: https://jekyll-theme-nix.michaelnordmeyer.com
icon: /icon.webp
icon_type: image/webp
title: Jekyll Theme Nix
author:
  name: Michael Nordmeyer
  uri: https://jekyll-theme-nix.michaelnordmeyer.com
description: "A barebones theme for Jekyll"

timezone: Europe/Berlin
ignore_theme_config: true
exclude: [jekyll-theme-nix*, LICENSE, README.md]
date_format: "%Y-%m-%d"

plugins:
  - jekyll-include-cache
  # - jekyll-redirect-from

## Jekyll build settings
kramdown:
  show_warnings: true
