## Remove URL for GitHub Pages plugin
#url: https://jekyll-theme-nix.michaelnordmeyer.com
title: Knoz
description: "Hi my name is"

plugins:
  - jekyll-feed
  - jekyll-include-cache
  - jekyll-redirect-from
  - jekyll-sitemap

## Jekyll build settings https://jekyllrb.com/docs/configuration/default/
exclude: [CODE_OF_CONDUCT.md, jekyll-theme-nix*, LICENSE, Rakefile.rb, README.md, screenshot.png]
ignore_theme_config: true # Since Jekyll 4.0, see: https://jekyllrb.com/docs/themes/#pre-configuring-theme-gems40, https://jekyllrb.com/docs/configuration/options/
include: [.well-known]
kramdown:
  show_warnings: true
  syntax_highlighter_opts:
    disable: true
liquid:
  # Configure Liquid’s parser
  error_mode: strict # default: warn
  # Configure Liquid’s renderer
  strict_filters: true # default: false
  # strict_variables: true # default: false
sass:
  style: compressed
strict_front_matter: true # default: false
# remote_theme: michaelnordmeyer/jekyll-theme-nix
# theme: jekyll-theme-nix
timezone: Europe/Berlin # default: local timezone

## Custom settings used by plugins and the theme
author:
  name: knoz
  email: knoz@example.com
  uri: http://knoz.org/
  copyright: Copyright © knoz
  # license_link: https://raw.githubusercontent.com/michaelnordmeyer/jekyll-theme-nix/main/LICENSE
# date_format: "%b %-d, %Y" # default: "%Y-%m-%d"
lang: en-US # default: en (is not by Jekyll, but used by many other plugins)
title_separator: " • " # default: " | "
## Custom theme settings
favicon: /icon.webp # optional, but mandatory if favicon_dark is used, needs to be 180x180
favicon_dark: /icon-dark.webp # optional, needs to be 180x180
theme_settings:
  # redirect_page_title: "Redirecting…" # default: "Redirecting…"
  # redirect_page_from: "Redirecting from" # default: "Redirecting from"
  # redirect_page_to: "to" # default: "to"
  # redirect_page_text: "Click here if you are not being redirected." # default: "Click here if you are not being redirected.""

## https://jekyllrb.com/docs/configuration/front-matter-defaults/
# Only works for all posts, but can work for a subset of pages
defaults:
  - scope:
      path: "" # an empty string here means all files in the project (allows globs, but is slow)
      type: posts # type (optional): posts, pages, drafts, or any collection
    values:
      layout: post
  - scope:
      path: ""
      type: pages
    values:
      layout: page
      permalink: /:path/:basename
  - scope:
      path: error
      type: pages
    values:
      layout: error
      sitemap: false
  - scope:
      path: ""
    values:
      layout: default
